[package]
name = "nucleoid-backend"
version = "0.1.0"
authors = ["Gegy <gegy1000@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3", features = ["codec"] }
warp = "0.2"
reqwest = { version = "0.10", features = ["rustls-tls", "json"], default-features = false }
futures = "0.3"

tokio-postgres = "0.5"

byteorder = "1.3"
bytes = "0.5"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

regex = "1.4"

serenity = { version = "0.9", default-features = false, features = ["builder", "cache", "client", "gateway", "model", "http", "rustls_backend"] }
async-trait = "0.1"

xtra = "0.5.0-rc.1"

thiserror = "1.0"

log = "0.4"
env_logger = "0.7.1"
